//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd", IsNullable=false)]
public partial class game {
    
    private teamType[] teamField;
    
    private possessionType possessionField;
    
    private lastEventType last_eventField;
    
    private scoringDriveTypeDrive[] scoring_drivesField;
    
    private string idField;
    
    private string awayField;
    
    private string homeField;
    
    private string clockField;
    
    private string quarterField;
    
    private System.DateTime scheduledField;
    
    private System.DateTime completedField;
    
    private bool completedFieldSpecified;
    
    private gameStatus statusField;
    
    private bool statusFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("team")]
    public teamType[] team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
    
    /// <remarks/>
    public possessionType possession {
        get {
            return this.possessionField;
        }
        set {
            this.possessionField = value;
        }
    }
    
    /// <remarks/>
    public lastEventType last_event {
        get {
            return this.last_eventField;
        }
        set {
            this.last_eventField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("drive", IsNullable=false)]
    public scoringDriveTypeDrive[] scoring_drives {
        get {
            return this.scoring_drivesField;
        }
        set {
            this.scoring_drivesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string away {
        get {
            return this.awayField;
        }
        set {
            this.awayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string home {
        get {
            return this.homeField;
        }
        set {
            this.homeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clock {
        get {
            return this.clockField;
        }
        set {
            this.clockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string quarter {
        get {
            return this.quarterField;
        }
        set {
            this.quarterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime scheduled {
        get {
            return this.scheduledField;
        }
        set {
            this.scheduledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime completed {
        get {
            return this.completedField;
        }
        set {
            this.completedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool completedSpecified {
        get {
            return this.completedFieldSpecified;
        }
        set {
            this.completedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public gameStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class teamType {
    
    private scoreType scoringField;
    
    private teamLeadersType leadersField;
    
    private teamTypePossession possessionField;
    
    private string idField;
    
    private string nameField;
    
    private string marketField;
    
    private string remaining_challengesField;
    
    private string remaining_timeoutsField;
    
    /// <remarks/>
    public scoreType scoring {
        get {
            return this.scoringField;
        }
        set {
            this.scoringField = value;
        }
    }
    
    /// <remarks/>
    public teamLeadersType leaders {
        get {
            return this.leadersField;
        }
        set {
            this.leadersField = value;
        }
    }
    
    /// <remarks/>
    public teamTypePossession possession {
        get {
            return this.possessionField;
        }
        set {
            this.possessionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string market {
        get {
            return this.marketField;
        }
        set {
            this.marketField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string remaining_challenges {
        get {
            return this.remaining_challengesField;
        }
        set {
            this.remaining_challengesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string remaining_timeouts {
        get {
            return this.remaining_timeoutsField;
        }
        set {
            this.remaining_timeoutsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class scoreType {
    
    private quarterType[] quarterField;
    
    private string pointsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quarter")]
    public quarterType[] quarter {
        get {
            return this.quarterField;
        }
        set {
            this.quarterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string points {
        get {
            return this.pointsField;
        }
        set {
            this.pointsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class quarterType {
    
    private string numberField;
    
    private string pointsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string points {
        get {
            return this.pointsField;
        }
        set {
            this.pointsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class linkType {
    
    private string hrefField;
    
    private string relField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rel {
        get {
            return this.relField;
        }
        set {
            this.relField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class playerType {
    
    private string idField;
    
    private string teamField;
    
    private string jerseyField;
    
    private string nameField;
    
    private string positionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string jersey {
        get {
            return this.jerseyField;
        }
        set {
            this.jerseyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class playType {
    
    private playerType[] participantsField;
    
    private string summaryField;
    
    private string sequenceField;
    
    private string clockField;
    
    private string typeField;
    
    private string downField;
    
    private string yfdField;
    
    private string sideField;
    
    private string yard_lineField;
    
    private System.DateTime updatedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("player", IsNullable=false)]
    public playerType[] participants {
        get {
            return this.participantsField;
        }
        set {
            this.participantsField = value;
        }
    }
    
    /// <remarks/>
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clock {
        get {
            return this.clockField;
        }
        set {
            this.clockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string down {
        get {
            return this.downField;
        }
        set {
            this.downField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yfd {
        get {
            return this.yfdField;
        }
        set {
            this.yfdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string side {
        get {
            return this.sideField;
        }
        set {
            this.sideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yard_line {
        get {
            return this.yard_lineField;
        }
        set {
            this.yard_lineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime updated {
        get {
            return this.updatedField;
        }
        set {
            this.updatedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class eventType {
    
    private object itemField;
    
    private string summaryField;
    
    private string clockField;
    
    private string sequenceField;
    
    private string typeField;
    
    private System.DateTime updatedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("timeout", typeof(eventTypeTimeout))]
    [System.Xml.Serialization.XmlElementAttribute("winner", typeof(eventTypeWinner))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clock {
        get {
            return this.clockField;
        }
        set {
            this.clockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime updated {
        get {
            return this.updatedField;
        }
        set {
            this.updatedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class eventTypeTimeout {
    
    private string numberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class eventTypeWinner {
    
    private string idField;
    
    private string outcomeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string outcome {
        get {
            return this.outcomeField;
        }
        set {
            this.outcomeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class lastEventType {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("event", typeof(eventType))]
    [System.Xml.Serialization.XmlElementAttribute("play", typeof(playType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class possessionType {
    
    private string teamField;
    
    private string sideField;
    
    private string yard_lineField;
    
    private string downField;
    
    private string yfdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string side {
        get {
            return this.sideField;
        }
        set {
            this.sideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yard_line {
        get {
            return this.yard_lineField;
        }
        set {
            this.yard_lineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string down {
        get {
            return this.downField;
        }
        set {
            this.downField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yfd {
        get {
            return this.yfdField;
        }
        set {
            this.yfdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class teamLeadersType {
    
    private teamLeadersTypePlayer[] passingField;
    
    private teamLeadersTypePlayer1[] rushingField;
    
    private teamLeadersTypePlayer2[] receivingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("player", IsNullable=false)]
    public teamLeadersTypePlayer[] passing {
        get {
            return this.passingField;
        }
        set {
            this.passingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("player", IsNullable=false)]
    public teamLeadersTypePlayer1[] rushing {
        get {
            return this.rushingField;
        }
        set {
            this.rushingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("player", IsNullable=false)]
    public teamLeadersTypePlayer2[] receiving {
        get {
            return this.receivingField;
        }
        set {
            this.receivingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class teamLeadersTypePlayer {
    
    private string idField;
    
    private string nameField;
    
    private string jerseyField;
    
    private string positionField;
    
    private string attField;
    
    private decimal avgField;
    
    private string cmpField;
    
    private decimal cmp_pctField;
    
    private decimal cmp_avgField;
    
    private bool cmp_avgFieldSpecified;
    
    private string fdField;
    
    private string intField;
    
    private decimal int_pctField;
    
    private string int_tdField;
    
    private string lgField;
    
    private decimal ratingField;
    
    private string sftyField;
    
    private string rz_attField;
    
    private string skField;
    
    private decimal sk_ydsField;
    
    private string tdField;
    
    private decimal td_pctField;
    
    private string ydsField;
    
    private string yds_10_plsField;
    
    private string yds_20_plsField;
    
    private string yds_30_plsField;
    
    private string yds_40_plsField;
    
    private string yds_50_plsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string jersey {
        get {
            return this.jerseyField;
        }
        set {
            this.jerseyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string att {
        get {
            return this.attField;
        }
        set {
            this.attField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal avg {
        get {
            return this.avgField;
        }
        set {
            this.avgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string cmp {
        get {
            return this.cmpField;
        }
        set {
            this.cmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal cmp_pct {
        get {
            return this.cmp_pctField;
        }
        set {
            this.cmp_pctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal cmp_avg {
        get {
            return this.cmp_avgField;
        }
        set {
            this.cmp_avgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cmp_avgSpecified {
        get {
            return this.cmp_avgFieldSpecified;
        }
        set {
            this.cmp_avgFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fd {
        get {
            return this.fdField;
        }
        set {
            this.fdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string @int {
        get {
            return this.intField;
        }
        set {
            this.intField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal int_pct {
        get {
            return this.int_pctField;
        }
        set {
            this.int_pctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string int_td {
        get {
            return this.int_tdField;
        }
        set {
            this.int_tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string lg {
        get {
            return this.lgField;
        }
        set {
            this.lgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sfty {
        get {
            return this.sftyField;
        }
        set {
            this.sftyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string rz_att {
        get {
            return this.rz_attField;
        }
        set {
            this.rz_attField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sk {
        get {
            return this.skField;
        }
        set {
            this.skField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal sk_yds {
        get {
            return this.sk_ydsField;
        }
        set {
            this.sk_ydsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string td {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal td_pct {
        get {
            return this.td_pctField;
        }
        set {
            this.td_pctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_10_pls {
        get {
            return this.yds_10_plsField;
        }
        set {
            this.yds_10_plsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_20_pls {
        get {
            return this.yds_20_plsField;
        }
        set {
            this.yds_20_plsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_30_pls {
        get {
            return this.yds_30_plsField;
        }
        set {
            this.yds_30_plsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_40_pls {
        get {
            return this.yds_40_plsField;
        }
        set {
            this.yds_40_plsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_50_pls {
        get {
            return this.yds_50_plsField;
        }
        set {
            this.yds_50_plsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class teamLeadersTypePlayer1 {
    
    private string idField;
    
    private string nameField;
    
    private string jerseyField;
    
    private string positionField;
    
    private string attField;
    
    private decimal avgField;
    
    private string fdField;
    
    private decimal fd_pctField;
    
    private bool fd_pctFieldSpecified;
    
    private string lgField;
    
    private string sftyField;
    
    private string rz_attField;
    
    private string fumField;
    
    private string tdField;
    
    private string ydsField;
    
    private string yds_10_plsField;
    
    private string yds_20_plsField;
    
    private string yds_30_plsField;
    
    private string yds_40_plsField;
    
    private string yds_50_plsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string jersey {
        get {
            return this.jerseyField;
        }
        set {
            this.jerseyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string att {
        get {
            return this.attField;
        }
        set {
            this.attField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal avg {
        get {
            return this.avgField;
        }
        set {
            this.avgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fd {
        get {
            return this.fdField;
        }
        set {
            this.fdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal fd_pct {
        get {
            return this.fd_pctField;
        }
        set {
            this.fd_pctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fd_pctSpecified {
        get {
            return this.fd_pctFieldSpecified;
        }
        set {
            this.fd_pctFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string lg {
        get {
            return this.lgField;
        }
        set {
            this.lgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sfty {
        get {
            return this.sftyField;
        }
        set {
            this.sftyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string rz_att {
        get {
            return this.rz_attField;
        }
        set {
            this.rz_attField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fum {
        get {
            return this.fumField;
        }
        set {
            this.fumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string td {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_10_pls {
        get {
            return this.yds_10_plsField;
        }
        set {
            this.yds_10_plsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_20_pls {
        get {
            return this.yds_20_plsField;
        }
        set {
            this.yds_20_plsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_30_pls {
        get {
            return this.yds_30_plsField;
        }
        set {
            this.yds_30_plsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_40_pls {
        get {
            return this.yds_40_plsField;
        }
        set {
            this.yds_40_plsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_50_pls {
        get {
            return this.yds_50_plsField;
        }
        set {
            this.yds_50_plsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class teamLeadersTypePlayer2 {
    
    private string idField;
    
    private string nameField;
    
    private string jerseyField;
    
    private string positionField;
    
    private decimal avgField;
    
    private string fdField;
    
    private string lgField;
    
    private string recField;
    
    private string tarField;
    
    private string rz_tarField;
    
    private string fumField;
    
    private string tdField;
    
    private string yacField;
    
    private string ydsField;
    
    private string yds_10_plsField;
    
    private string yds_20_plsField;
    
    private string yds_30_plsField;
    
    private string yds_40_plsField;
    
    private string yds_50_plsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string jersey {
        get {
            return this.jerseyField;
        }
        set {
            this.jerseyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal avg {
        get {
            return this.avgField;
        }
        set {
            this.avgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fd {
        get {
            return this.fdField;
        }
        set {
            this.fdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string lg {
        get {
            return this.lgField;
        }
        set {
            this.lgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string rec {
        get {
            return this.recField;
        }
        set {
            this.recField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string tar {
        get {
            return this.tarField;
        }
        set {
            this.tarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string rz_tar {
        get {
            return this.rz_tarField;
        }
        set {
            this.rz_tarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fum {
        get {
            return this.fumField;
        }
        set {
            this.fumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string td {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yac {
        get {
            return this.yacField;
        }
        set {
            this.yacField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_10_pls {
        get {
            return this.yds_10_plsField;
        }
        set {
            this.yds_10_plsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_20_pls {
        get {
            return this.yds_20_plsField;
        }
        set {
            this.yds_20_plsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_30_pls {
        get {
            return this.yds_30_plsField;
        }
        set {
            this.yds_30_plsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_40_pls {
        get {
            return this.yds_40_plsField;
        }
        set {
            this.yds_40_plsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds_50_pls {
        get {
            return this.yds_50_plsField;
        }
        set {
            this.yds_50_plsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class teamTypePossession {
    
    private string timeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class scoringDriveTypeDrive {
    
    private scoringDriveTypeDriveScore[] scoreField;
    
    private string clockField;
    
    private string quarterField;
    
    private string sequenceField;
    
    private string teamField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("score")]
    public scoringDriveTypeDriveScore[] score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clock {
        get {
            return this.clockField;
        }
        set {
            this.clockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string quarter {
        get {
            return this.quarterField;
        }
        set {
            this.quarterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public partial class scoringDriveTypeDriveScore {
    
    private string summaryField;
    
    private linkType[] linksField;
    
    private string clockField;
    
    private string pointsField;
    
    private string typeField;
    
    private string quarterField;
    
    /// <remarks/>
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("link", IsNullable=false)]
    public linkType[] links {
        get {
            return this.linksField;
        }
        set {
            this.linksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clock {
        get {
            return this.clockField;
        }
        set {
            this.clockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string points {
        get {
            return this.pointsField;
        }
        set {
            this.pointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string quarter {
        get {
            return this.quarterField;
        }
        set {
            this.quarterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-boxscore-v1.0.xsd")]
public enum gameStatus {
    
    /// <remarks/>
    scheduled,
    
    /// <remarks/>
    created,
    
    /// <remarks/>
    inprogress,
    
    /// <remarks/>
    complete,
    
    /// <remarks/>
    closed,
    
    /// <remarks/>
    reopened,
}
