//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace GameSummary
{

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd", IsNullable = false)]
    public partial class game
    {

        private teamSummaryType[] teamField;

        private string idField;

        private System.DateTime scheduledField;

        private string awayField;

        private string homeField;

        private gameStatus statusField;

        private bool statusFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("team")]
        public teamSummaryType[] team
        {
            get
            {
                return this.teamField;
            }
            set
            {
                this.teamField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime scheduled
        {
            get
            {
                return this.scheduledField;
            }
            set
            {
                this.scheduledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string away
        {
            get
            {
                return this.awayField;
            }
            set
            {
                this.awayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string home
        {
            get
            {
                return this.homeField;
            }
            set
            {
                this.homeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public gameStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class teamSummaryType
    {

        private teamSummaryTypeFirst_downs first_downsField;

        private downEfficiencyType third_down_efficiencyField;

        private downEfficiencyType fourth_down_efficiencyField;

        private netYardageType total_yardsField;

        private netYardageType rushing_yardsField;

        private passingType passingField;

        private returnYardageType return_yardsField;

        private teamSummaryTypeKickoffs kickoffsField;

        private teamSummaryTypePunts puntsField;

        private teamSummaryTypePenalties penaltiesField;

        private teamSummaryTypeFumbles fumblesField;

        private teamSummaryTypeTouchdowns touchdownsField;

        private teamSummaryTypeExtra_points extra_pointsField;

        private kickConversionType field_goalsField;

        private zoneEfficiencyType redzone_efficiencyField;

        private zoneEfficiencyType goal_efficiencyField;

        private teamSummaryTypeSafeties safetiesField;

        private teamSummaryTypeTurnovers turnoversField;

        private string final_scoreField;

        private string possession_timeField;

        private string idField;

        private string marketField;

        private string nameField;

        /// <remarks/>
        public teamSummaryTypeFirst_downs first_downs
        {
            get
            {
                return this.first_downsField;
            }
            set
            {
                this.first_downsField = value;
            }
        }

        /// <remarks/>
        public downEfficiencyType third_down_efficiency
        {
            get
            {
                return this.third_down_efficiencyField;
            }
            set
            {
                this.third_down_efficiencyField = value;
            }
        }

        /// <remarks/>
        public downEfficiencyType fourth_down_efficiency
        {
            get
            {
                return this.fourth_down_efficiencyField;
            }
            set
            {
                this.fourth_down_efficiencyField = value;
            }
        }

        /// <remarks/>
        public netYardageType total_yards
        {
            get
            {
                return this.total_yardsField;
            }
            set
            {
                this.total_yardsField = value;
            }
        }

        /// <remarks/>
        public netYardageType rushing_yards
        {
            get
            {
                return this.rushing_yardsField;
            }
            set
            {
                this.rushing_yardsField = value;
            }
        }

        /// <remarks/>
        public passingType passing
        {
            get
            {
                return this.passingField;
            }
            set
            {
                this.passingField = value;
            }
        }

        /// <remarks/>
        public returnYardageType return_yards
        {
            get
            {
                return this.return_yardsField;
            }
            set
            {
                this.return_yardsField = value;
            }
        }

        /// <remarks/>
        public teamSummaryTypeKickoffs kickoffs
        {
            get
            {
                return this.kickoffsField;
            }
            set
            {
                this.kickoffsField = value;
            }
        }

        /// <remarks/>
        public teamSummaryTypePunts punts
        {
            get
            {
                return this.puntsField;
            }
            set
            {
                this.puntsField = value;
            }
        }

        /// <remarks/>
        public teamSummaryTypePenalties penalties
        {
            get
            {
                return this.penaltiesField;
            }
            set
            {
                this.penaltiesField = value;
            }
        }

        /// <remarks/>
        public teamSummaryTypeFumbles fumbles
        {
            get
            {
                return this.fumblesField;
            }
            set
            {
                this.fumblesField = value;
            }
        }

        /// <remarks/>
        public teamSummaryTypeTouchdowns touchdowns
        {
            get
            {
                return this.touchdownsField;
            }
            set
            {
                this.touchdownsField = value;
            }
        }

        /// <remarks/>
        public teamSummaryTypeExtra_points extra_points
        {
            get
            {
                return this.extra_pointsField;
            }
            set
            {
                this.extra_pointsField = value;
            }
        }

        /// <remarks/>
        public kickConversionType field_goals
        {
            get
            {
                return this.field_goalsField;
            }
            set
            {
                this.field_goalsField = value;
            }
        }

        /// <remarks/>
        public zoneEfficiencyType redzone_efficiency
        {
            get
            {
                return this.redzone_efficiencyField;
            }
            set
            {
                this.redzone_efficiencyField = value;
            }
        }

        /// <remarks/>
        public zoneEfficiencyType goal_efficiency
        {
            get
            {
                return this.goal_efficiencyField;
            }
            set
            {
                this.goal_efficiencyField = value;
            }
        }

        /// <remarks/>
        public teamSummaryTypeSafeties safeties
        {
            get
            {
                return this.safetiesField;
            }
            set
            {
                this.safetiesField = value;
            }
        }

        /// <remarks/>
        public teamSummaryTypeTurnovers turnovers
        {
            get
            {
                return this.turnoversField;
            }
            set
            {
                this.turnoversField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string final_score
        {
            get
            {
                return this.final_scoreField;
            }
            set
            {
                this.final_scoreField = value;
            }
        }

        /// <remarks/>
        public string possession_time
        {
            get
            {
                return this.possession_timeField;
            }
            set
            {
                this.possession_timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string market
        {
            get
            {
                return this.marketField;
            }
            set
            {
                this.marketField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class teamSummaryTypeFirst_downs : downConversionType
    {

        private string totalField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(downEfficiencyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class downConversionType
    {

        private string passingField;

        private string rushingField;

        private string penaltyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string passing
        {
            get
            {
                return this.passingField;
            }
            set
            {
                this.passingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string rushing
        {
            get
            {
                return this.rushingField;
            }
            set
            {
                this.rushingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string penalty
        {
            get
            {
                return this.penaltyField;
            }
            set
            {
                this.penaltyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class zoneEfficiencyType
    {

        private string attField;

        private decimal pctField;

        private string tdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string att
        {
            get
            {
                return this.attField;
            }
            set
            {
                this.attField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pct
        {
            get
            {
                return this.pctField;
            }
            set
            {
                this.pctField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string td
        {
            get
            {
                return this.tdField;
            }
            set
            {
                this.tdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class kickConversionType
    {

        private string attField;

        private string blkField;

        private string madeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string att
        {
            get
            {
                return this.attField;
            }
            set
            {
                this.attField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string blk
        {
            get
            {
                return this.blkField;
            }
            set
            {
                this.blkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string made
        {
            get
            {
                return this.madeField;
            }
            set
            {
                this.madeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class returnAttemptType
    {

        private string numberField;

        private string ydsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string yds
        {
            get
            {
                return this.ydsField;
            }
            set
            {
                this.ydsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class returnYardageType
    {

        private returnAttemptType punt_returnField;

        private returnAttemptType kickoff_returnField;

        private returnAttemptType int_returnField;

        private string totalField;

        /// <remarks/>
        public returnAttemptType punt_return
        {
            get
            {
                return this.punt_returnField;
            }
            set
            {
                this.punt_returnField = value;
            }
        }

        /// <remarks/>
        public returnAttemptType kickoff_return
        {
            get
            {
                return this.kickoff_returnField;
            }
            set
            {
                this.kickoff_returnField = value;
            }
        }

        /// <remarks/>
        public returnAttemptType int_return
        {
            get
            {
                return this.int_returnField;
            }
            set
            {
                this.int_returnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class passingType
    {

        private passingTypeYards yardsField;

        private string attField;

        private decimal avgField;

        private bool avgFieldSpecified;

        private string cmpField;

        private string intField;

        private string sackField;

        /// <remarks/>
        public passingTypeYards yards
        {
            get
            {
                return this.yardsField;
            }
            set
            {
                this.yardsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string att
        {
            get
            {
                return this.attField;
            }
            set
            {
                this.attField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal avg
        {
            get
            {
                return this.avgField;
            }
            set
            {
                this.avgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avgSpecified
        {
            get
            {
                return this.avgFieldSpecified;
            }
            set
            {
                this.avgFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string cmp
        {
            get
            {
                return this.cmpField;
            }
            set
            {
                this.cmpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string @int
        {
            get
            {
                return this.intField;
            }
            set
            {
                this.intField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string sack
        {
            get
            {
                return this.sackField;
            }
            set
            {
                this.sackField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class passingTypeYards
    {

        private string gross_ydsField;

        private decimal net_ydsField;

        private decimal sack_ydsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string gross_yds
        {
            get
            {
                return this.gross_ydsField;
            }
            set
            {
                this.gross_ydsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_yds
        {
            get
            {
                return this.net_ydsField;
            }
            set
            {
                this.net_ydsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal sack_yds
        {
            get
            {
                return this.sack_ydsField;
            }
            set
            {
                this.sack_ydsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class netYardageType
    {

        private decimal avgField;

        private string playsField;

        private decimal ydsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal avg
        {
            get
            {
                return this.avgField;
            }
            set
            {
                this.avgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string plays
        {
            get
            {
                return this.playsField;
            }
            set
            {
                this.playsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal yds
        {
            get
            {
                return this.ydsField;
            }
            set
            {
                this.ydsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class downEfficiencyType : downConversionType
    {

        private string attField;

        private string convertedField;

        private decimal pctField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string att
        {
            get
            {
                return this.attField;
            }
            set
            {
                this.attField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string converted
        {
            get
            {
                return this.convertedField;
            }
            set
            {
                this.convertedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pct
        {
            get
            {
                return this.pctField;
            }
            set
            {
                this.pctField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class teamSummaryTypeKickoffs
    {

        private string endzoneField;

        private string numberField;

        private string tbField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string endzone
        {
            get
            {
                return this.endzoneField;
            }
            set
            {
                this.endzoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string tb
        {
            get
            {
                return this.tbField;
            }
            set
            {
                this.tbField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class teamSummaryTypePunts
    {

        private decimal avgField;

        private string blkField;

        private decimal net_avgField;

        private string numberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal avg
        {
            get
            {
                return this.avgField;
            }
            set
            {
                this.avgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string blk
        {
            get
            {
                return this.blkField;
            }
            set
            {
                this.blkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_avg
        {
            get
            {
                return this.net_avgField;
            }
            set
            {
                this.net_avgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class teamSummaryTypePenalties
    {

        private string numberField;

        private string ydsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string yds
        {
            get
            {
                return this.ydsField;
            }
            set
            {
                this.ydsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class teamSummaryTypeFumbles
    {

        private string lostField;

        private string numberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string lost
        {
            get
            {
                return this.lostField;
            }
            set
            {
                this.lostField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class teamSummaryTypeTouchdowns
    {

        private string passingField;

        private string rushingField;

        private string interceptionField;

        private string fumble_returnField;

        private string punt_returnField;

        private string kickoff_returnField;

        private string field_goal_returnField;

        private string numberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string passing
        {
            get
            {
                return this.passingField;
            }
            set
            {
                this.passingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string rushing
        {
            get
            {
                return this.rushingField;
            }
            set
            {
                this.rushingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string interception
        {
            get
            {
                return this.interceptionField;
            }
            set
            {
                this.interceptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string fumble_return
        {
            get
            {
                return this.fumble_returnField;
            }
            set
            {
                this.fumble_returnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string punt_return
        {
            get
            {
                return this.punt_returnField;
            }
            set
            {
                this.punt_returnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string kickoff_return
        {
            get
            {
                return this.kickoff_returnField;
            }
            set
            {
                this.kickoff_returnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string field_goal_return
        {
            get
            {
                return this.field_goal_returnField;
            }
            set
            {
                this.field_goal_returnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class teamSummaryTypeExtra_points
    {

        private kickConversionType kickingField;

        private kickConversionType two_pointsField;

        private string attField;

        private string madeField;

        /// <remarks/>
        public kickConversionType kicking
        {
            get
            {
                return this.kickingField;
            }
            set
            {
                this.kickingField = value;
            }
        }

        /// <remarks/>
        public kickConversionType two_points
        {
            get
            {
                return this.two_pointsField;
            }
            set
            {
                this.two_pointsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string att
        {
            get
            {
                return this.attField;
            }
            set
            {
                this.attField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string made
        {
            get
            {
                return this.madeField;
            }
            set
            {
                this.madeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class teamSummaryTypeSafeties
    {

        private string numberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public partial class teamSummaryTypeTurnovers
    {

        private string numberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/summary-v1.0.xsd")]
    public enum gameStatus
    {

        /// <remarks/>
        scheduled,

        /// <remarks/>
        created,

        /// <remarks/>
        inprogress,

        /// <remarks/>
        complete,

        /// <remarks/>
        closed,

        /// <remarks/>
        reopened,
    }
}