//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace Injuries
{

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/roster-v1.0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/roster-v1.0.xsd", IsNullable = false)]
    public partial class game
    {

        private teamType[] teamField;

        private string idField;

        private System.DateTime scheduledField;

        private string awayField;

        private string homeField;

        private gameStatus statusField;

        private bool statusFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("team")]
        public teamType[] team
        {
            get
            {
                return this.teamField;
            }
            set
            {
                this.teamField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime scheduled
        {
            get
            {
                return this.scheduledField;
            }
            set
            {
                this.scheduledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string away
        {
            get
            {
                return this.awayField;
            }
            set
            {
                this.awayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string home
        {
            get
            {
                return this.homeField;
            }
            set
            {
                this.homeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public gameStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/roster-v1.0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("team", Namespace = "http://feed.elasticstats.com/schema/nfl/roster-v1.0.xsd", IsNullable = false)]
    public partial class teamType
    {

        private playerType[] playerField;

        private string idField;

        private string nameField;

        private string marketField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("player")]
        public playerType[] player
        {
            get
            {
                return this.playerField;
            }
            set
            {
                this.playerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string market
        {
            get
            {
                return this.marketField;
            }
            set
            {
                this.marketField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/roster-v1.0.xsd")]
    public partial class playerType
    {

        private injuryType[] injuriesField;

        private string idField;

        private string name_abbrField;

        private string name_firstField;

        private string name_fullField;

        private string name_lastField;

        private string jersey_numberField;

        private string positionField;

        private string birthdateField;

        private string birth_placeField;

        private string high_schoolField;

        private string collegeField;

        private string heightField;

        private string weightField;

        private string salaryField;

        private string statusField;

        private string draft_teamField;

        private string draft_pickField;

        private string draft_roundField;

        private string joined_leagueField;

        private string experienceField;

        private bool startedField;

        private bool startedFieldSpecified;

        private bool playedField;

        private bool playedFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("injury", IsNullable = false)]
        public injuryType[] injuries
        {
            get
            {
                return this.injuriesField;
            }
            set
            {
                this.injuriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name_abbr
        {
            get
            {
                return this.name_abbrField;
            }
            set
            {
                this.name_abbrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name_first
        {
            get
            {
                return this.name_firstField;
            }
            set
            {
                this.name_firstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name_full
        {
            get
            {
                return this.name_fullField;
            }
            set
            {
                this.name_fullField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name_last
        {
            get
            {
                return this.name_lastField;
            }
            set
            {
                this.name_lastField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string jersey_number
        {
            get
            {
                return this.jersey_numberField;
            }
            set
            {
                this.jersey_numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string birthdate
        {
            get
            {
                return this.birthdateField;
            }
            set
            {
                this.birthdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string birth_place
        {
            get
            {
                return this.birth_placeField;
            }
            set
            {
                this.birth_placeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string high_school
        {
            get
            {
                return this.high_schoolField;
            }
            set
            {
                this.high_schoolField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string college
        {
            get
            {
                return this.collegeField;
            }
            set
            {
                this.collegeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string salary
        {
            get
            {
                return this.salaryField;
            }
            set
            {
                this.salaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string draft_team
        {
            get
            {
                return this.draft_teamField;
            }
            set
            {
                this.draft_teamField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string draft_pick
        {
            get
            {
                return this.draft_pickField;
            }
            set
            {
                this.draft_pickField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string draft_round
        {
            get
            {
                return this.draft_roundField;
            }
            set
            {
                this.draft_roundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string joined_league
        {
            get
            {
                return this.joined_leagueField;
            }
            set
            {
                this.joined_leagueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string experience
        {
            get
            {
                return this.experienceField;
            }
            set
            {
                this.experienceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool started
        {
            get
            {
                return this.startedField;
            }
            set
            {
                this.startedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startedSpecified
        {
            get
            {
                return this.startedFieldSpecified;
            }
            set
            {
                this.startedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool played
        {
            get
            {
                return this.playedField;
            }
            set
            {
                this.playedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool playedSpecified
        {
            get
            {
                return this.playedFieldSpecified;
            }
            set
            {
                this.playedFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://feed.elasticstats.com/schema/nfl/roster-v1.0.xsd")]
    public partial class injuryType
    {

        private string descriptionField;

        private string notesField;

        private string idField;

        private System.DateTime start_dateField;

        private string game_statusField;

        private string practice_statusField;

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime start_date
        {
            get
            {
                return this.start_dateField;
            }
            set
            {
                this.start_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string game_status
        {
            get
            {
                return this.game_statusField;
            }
            set
            {
                this.game_statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string practice_status
        {
            get
            {
                return this.practice_statusField;
            }
            set
            {
                this.practice_statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://feed.elasticstats.com/schema/nfl/roster-v1.0.xsd")]
    public enum gameStatus
    {

        /// <remarks/>
        scheduled,

        /// <remarks/>
        created,

        /// <remarks/>
        inprogress,

        /// <remarks/>
        complete,

        /// <remarks/>
        closed,

        /// <remarks/>
        reopened,
    }
}