//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace PlaySummary{
// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute("play", Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd", IsNullable=false)]
public partial class playType {
    
    private string summaryField;
    
    private situationType start_situationField;
    
    private situationType end_situationField;
    
    private scoreType scoreField;
    
    private playerType[] statisticsField;
    
    private string clockField;
    
    private string controllerField;
    
    private string gameField;
    
    private string idField;
    
    private bool officialField;
    
    private string quarterField;
    
    private string typeField;
    
    private System.DateTime updatedField;
    
    private bool updatedFieldSpecified;
    
    private string formationField;
    
    private string directionField;
    
    private string distanceField;
    
    private string defense_formationField;
    
    private string defense_actionField;
    
    /// <remarks/>
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    public situationType start_situation {
        get {
            return this.start_situationField;
        }
        set {
            this.start_situationField = value;
        }
    }
    
    /// <remarks/>
    public situationType end_situation {
        get {
            return this.end_situationField;
        }
        set {
            this.end_situationField = value;
        }
    }
    
    /// <remarks/>
    public scoreType score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("player", IsNullable=false)]
    public playerType[] statistics {
        get {
            return this.statisticsField;
        }
        set {
            this.statisticsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clock {
        get {
            return this.clockField;
        }
        set {
            this.clockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string controller {
        get {
            return this.controllerField;
        }
        set {
            this.controllerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string game {
        get {
            return this.gameField;
        }
        set {
            this.gameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool official {
        get {
            return this.officialField;
        }
        set {
            this.officialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string quarter {
        get {
            return this.quarterField;
        }
        set {
            this.quarterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime updated {
        get {
            return this.updatedField;
        }
        set {
            this.updatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool updatedSpecified {
        get {
            return this.updatedFieldSpecified;
        }
        set {
            this.updatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string formation {
        get {
            return this.formationField;
        }
        set {
            this.formationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string direction {
        get {
            return this.directionField;
        }
        set {
            this.directionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defense_formation {
        get {
            return this.defense_formationField;
        }
        set {
            this.defense_formationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defense_action {
        get {
            return this.defense_actionField;
        }
        set {
            this.defense_actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class situationType {
    
    private string teamField;
    
    private string sideField;
    
    private string yard_lineField;
    
    private string downField;
    
    private string yfdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string side {
        get {
            return this.sideField;
        }
        set {
            this.sideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yard_line {
        get {
            return this.yard_lineField;
        }
        set {
            this.yard_lineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string down {
        get {
            return this.downField;
        }
        set {
            this.downField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yfd {
        get {
            return this.yfdField;
        }
        set {
            this.yfdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerType {
    
    private playerTypeDefense defenseField;
    
    private playerTypeRushing rushingField;
    
    private playerTypeReceiving receivingField;
    
    private playerTypePunt_return punt_returnField;
    
    private playerTypePunting puntingField;
    
    private playerTypePenalty penaltyField;
    
    private playerTypePassing passingField;
    
    private playerTypeKick_return kick_returnField;
    
    private playerTypeKickoffs kickoffsField;
    
    private playerTypeInterception_return interception_returnField;
    
    private playerTypeFumble_return fumble_returnField;
    
    private playerTypeField_goal_return field_goal_returnField;
    
    private playerTypeField_goal field_goalField;
    
    private playerTypeExtra_point extra_pointField;
    
    private playerTypeTwo_point_conversion two_point_conversionField;
    
    private playerTypeBlocked_punt_return blocked_punt_returnField;
    
    private playerTypeBlocked_field_goal_return blocked_field_goal_returnField;
    
    private string idField;
    
    private string nameField;
    
    private string teamField;
    
    private string jerseyField;
    
    private string positionField;
    
    /// <remarks/>
    public playerTypeDefense defense {
        get {
            return this.defenseField;
        }
        set {
            this.defenseField = value;
        }
    }
    
    /// <remarks/>
    public playerTypeRushing rushing {
        get {
            return this.rushingField;
        }
        set {
            this.rushingField = value;
        }
    }
    
    /// <remarks/>
    public playerTypeReceiving receiving {
        get {
            return this.receivingField;
        }
        set {
            this.receivingField = value;
        }
    }
    
    /// <remarks/>
    public playerTypePunt_return punt_return {
        get {
            return this.punt_returnField;
        }
        set {
            this.punt_returnField = value;
        }
    }
    
    /// <remarks/>
    public playerTypePunting punting {
        get {
            return this.puntingField;
        }
        set {
            this.puntingField = value;
        }
    }
    
    /// <remarks/>
    public playerTypePenalty penalty {
        get {
            return this.penaltyField;
        }
        set {
            this.penaltyField = value;
        }
    }
    
    /// <remarks/>
    public playerTypePassing passing {
        get {
            return this.passingField;
        }
        set {
            this.passingField = value;
        }
    }
    
    /// <remarks/>
    public playerTypeKick_return kick_return {
        get {
            return this.kick_returnField;
        }
        set {
            this.kick_returnField = value;
        }
    }
    
    /// <remarks/>
    public playerTypeKickoffs kickoffs {
        get {
            return this.kickoffsField;
        }
        set {
            this.kickoffsField = value;
        }
    }
    
    /// <remarks/>
    public playerTypeInterception_return interception_return {
        get {
            return this.interception_returnField;
        }
        set {
            this.interception_returnField = value;
        }
    }
    
    /// <remarks/>
    public playerTypeFumble_return fumble_return {
        get {
            return this.fumble_returnField;
        }
        set {
            this.fumble_returnField = value;
        }
    }
    
    /// <remarks/>
    public playerTypeField_goal_return field_goal_return {
        get {
            return this.field_goal_returnField;
        }
        set {
            this.field_goal_returnField = value;
        }
    }
    
    /// <remarks/>
    public playerTypeField_goal field_goal {
        get {
            return this.field_goalField;
        }
        set {
            this.field_goalField = value;
        }
    }
    
    /// <remarks/>
    public playerTypeExtra_point extra_point {
        get {
            return this.extra_pointField;
        }
        set {
            this.extra_pointField = value;
        }
    }
    
    /// <remarks/>
    public playerTypeTwo_point_conversion two_point_conversion {
        get {
            return this.two_point_conversionField;
        }
        set {
            this.two_point_conversionField = value;
        }
    }
    
    /// <remarks/>
    public playerTypeBlocked_punt_return blocked_punt_return {
        get {
            return this.blocked_punt_returnField;
        }
        set {
            this.blocked_punt_returnField = value;
        }
    }
    
    /// <remarks/>
    public playerTypeBlocked_field_goal_return blocked_field_goal_return {
        get {
            return this.blocked_field_goal_returnField;
        }
        set {
            this.blocked_field_goal_returnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string jersey {
        get {
            return this.jerseyField;
        }
        set {
            this.jerseyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeDefense {
    
    private string astField;
    
    private string categoryField;
    
    private string force_fumField;
    
    private string intField;
    
    private string sackField;
    
    private decimal sack_ydsField;
    
    private string sftyField;
    
    private string tackleField;
    
    private string tlostField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string ast {
        get {
            return this.astField;
        }
        set {
            this.astField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string force_fum {
        get {
            return this.force_fumField;
        }
        set {
            this.force_fumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string @int {
        get {
            return this.intField;
        }
        set {
            this.intField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sack {
        get {
            return this.sackField;
        }
        set {
            this.sackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal sack_yds {
        get {
            return this.sack_ydsField;
        }
        set {
            this.sack_ydsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sfty {
        get {
            return this.sftyField;
        }
        set {
            this.sftyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string tackle {
        get {
            return this.tackleField;
        }
        set {
            this.tackleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string tlost {
        get {
            return this.tlostField;
        }
        set {
            this.tlostField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeRushing {
    
    private string attField;
    
    private string fdField;
    
    private string fumField;
    
    private string rz_attField;
    
    private string sftyField;
    
    private string tdField;
    
    private string ydsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string att {
        get {
            return this.attField;
        }
        set {
            this.attField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fd {
        get {
            return this.fdField;
        }
        set {
            this.fdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fum {
        get {
            return this.fumField;
        }
        set {
            this.fumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string rz_att {
        get {
            return this.rz_attField;
        }
        set {
            this.rz_attField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sfty {
        get {
            return this.sftyField;
        }
        set {
            this.sftyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string td {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeReceiving {
    
    private string fdField;
    
    private string fumField;
    
    private string recField;
    
    private string rz_tarField;
    
    private string tarField;
    
    private string tdField;
    
    private string yacField;
    
    private string ydsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fd {
        get {
            return this.fdField;
        }
        set {
            this.fdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fum {
        get {
            return this.fumField;
        }
        set {
            this.fumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string rec {
        get {
            return this.recField;
        }
        set {
            this.recField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string rz_tar {
        get {
            return this.rz_tarField;
        }
        set {
            this.rz_tarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string tar {
        get {
            return this.tarField;
        }
        set {
            this.tarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string td {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yac {
        get {
            return this.yacField;
        }
        set {
            this.yacField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypePunt_return {
    
    private string fcField;
    
    private string returnsField;
    
    private string tdField;
    
    private string ydsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fc {
        get {
            return this.fcField;
        }
        set {
            this.fcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string returns {
        get {
            return this.returnsField;
        }
        set {
            this.returnsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string td {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypePunting {
    
    private string blkField;
    
    private string in20Field;
    
    private string net_ydsField;
    
    private string puntsField;
    
    private string retField;
    
    private string tbField;
    
    private string ydsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string blk {
        get {
            return this.blkField;
        }
        set {
            this.blkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string in20 {
        get {
            return this.in20Field;
        }
        set {
            this.in20Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string net_yds {
        get {
            return this.net_ydsField;
        }
        set {
            this.net_ydsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string punts {
        get {
            return this.puntsField;
        }
        set {
            this.puntsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string ret {
        get {
            return this.retField;
        }
        set {
            this.retField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string tb {
        get {
            return this.tbField;
        }
        set {
            this.tbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypePenalty {
    
    private string fdField;
    
    private string ydsField;
    
    private string abbrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fd {
        get {
            return this.fdField;
        }
        set {
            this.fdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string abbr {
        get {
            return this.abbrField;
        }
        set {
            this.abbrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypePassing {
    
    private string attField;
    
    private string cmpField;
    
    private string fdField;
    
    private string intField;
    
    private string rz_attField;
    
    private string sftyField;
    
    private string skField;
    
    private string sk_ydsField;
    
    private string tdField;
    
    private string ydsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string att {
        get {
            return this.attField;
        }
        set {
            this.attField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string cmp {
        get {
            return this.cmpField;
        }
        set {
            this.cmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fd {
        get {
            return this.fdField;
        }
        set {
            this.fdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string @int {
        get {
            return this.intField;
        }
        set {
            this.intField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string rz_att {
        get {
            return this.rz_attField;
        }
        set {
            this.rz_attField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sfty {
        get {
            return this.sftyField;
        }
        set {
            this.sftyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sk {
        get {
            return this.skField;
        }
        set {
            this.skField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sk_yds {
        get {
            return this.sk_ydsField;
        }
        set {
            this.sk_ydsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string td {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeKick_return {
    
    private string fcField;
    
    private string returnsField;
    
    private string tdField;
    
    private string ydsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fc {
        get {
            return this.fcField;
        }
        set {
            this.fcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string returns {
        get {
            return this.returnsField;
        }
        set {
            this.returnsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string td {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeKickoffs {
    
    private string endzoneField;
    
    private string in20Field;
    
    private string kicksField;
    
    private string net_ydsField;
    
    private string retField;
    
    private string tbField;
    
    private string ydsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string endzone {
        get {
            return this.endzoneField;
        }
        set {
            this.endzoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string in20 {
        get {
            return this.in20Field;
        }
        set {
            this.in20Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string kicks {
        get {
            return this.kicksField;
        }
        set {
            this.kicksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string net_yds {
        get {
            return this.net_ydsField;
        }
        set {
            this.net_ydsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string ret {
        get {
            return this.retField;
        }
        set {
            this.retField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string tb {
        get {
            return this.tbField;
        }
        set {
            this.tbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeInterception_return {
    
    private string fcField;
    
    private string returnsField;
    
    private string tdField;
    
    private string ydsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fc {
        get {
            return this.fcField;
        }
        set {
            this.fcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string returns {
        get {
            return this.returnsField;
        }
        set {
            this.returnsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string td {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeFumble_return {
    
    private string categoryField;
    
    private string own_recField;
    
    private string opp_recField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string own_rec {
        get {
            return this.own_recField;
        }
        set {
            this.own_recField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string opp_rec {
        get {
            return this.opp_recField;
        }
        set {
            this.opp_recField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeField_goal_return {
    
    private string fcField;
    
    private string returnsField;
    
    private string tdField;
    
    private string ydsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fc {
        get {
            return this.fcField;
        }
        set {
            this.fcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string returns {
        get {
            return this.returnsField;
        }
        set {
            this.returnsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string td {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeField_goal {
    
    private string attField;
    
    private string att_ydsField;
    
    private string blkField;
    
    private string madeField;
    
    private string retField;
    
    private string ydsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string att {
        get {
            return this.attField;
        }
        set {
            this.attField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string att_yds {
        get {
            return this.att_ydsField;
        }
        set {
            this.att_ydsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string blk {
        get {
            return this.blkField;
        }
        set {
            this.blkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string made {
        get {
            return this.madeField;
        }
        set {
            this.madeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string ret {
        get {
            return this.retField;
        }
        set {
            this.retField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeExtra_point {
    
    private string attField;
    
    private string blkField;
    
    private string madeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string att {
        get {
            return this.attField;
        }
        set {
            this.attField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string blk {
        get {
            return this.blkField;
        }
        set {
            this.blkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string made {
        get {
            return this.madeField;
        }
        set {
            this.madeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeTwo_point_conversion {
    
    private string attField;
    
    private string cmpField;
    
    private string categoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string att {
        get {
            return this.attField;
        }
        set {
            this.attField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string cmp {
        get {
            return this.cmpField;
        }
        set {
            this.cmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeBlocked_punt_return {
    
    private string fcField;
    
    private string returnsField;
    
    private string tdField;
    
    private string ydsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fc {
        get {
            return this.fcField;
        }
        set {
            this.fcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string returns {
        get {
            return this.returnsField;
        }
        set {
            this.returnsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string td {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class playerTypeBlocked_field_goal_return {
    
    private string fcField;
    
    private string returnsField;
    
    private string tdField;
    
    private string ydsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string fc {
        get {
            return this.fcField;
        }
        set {
            this.fcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string returns {
        get {
            return this.returnsField;
        }
        set {
            this.returnsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string td {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string yds {
        get {
            return this.ydsField;
        }
        set {
            this.ydsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/extended-play-v1.0.xsd")]
public partial class scoreType {
    
    private string pointsField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string points {
        get {
            return this.pointsField;
        }
        set {
            this.pointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}
}