//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/standings-v1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/standings-v1.0.xsd", IsNullable=false)]
public partial class standings {
    
    private conferenceType[] conferenceField;
    
    private string seasonField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("conference")]
    public conferenceType[] conference {
        get {
            return this.conferenceField;
        }
        set {
            this.conferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string season {
        get {
            return this.seasonField;
        }
        set {
            this.seasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/standings-v1.0.xsd")]
public partial class conferenceType {
    
    private divisionType[] divisionField;
    
    private string idField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("division")]
    public divisionType[] division {
        get {
            return this.divisionField;
        }
        set {
            this.divisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/standings-v1.0.xsd")]
public partial class divisionType {
    
    private standingsType[] teamField;
    
    private string idField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("team")]
    public standingsType[] team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/standings-v1.0.xsd")]
public partial class standingsType {
    
    private recordType overallField;
    
    private recordType in_conferenceField;
    
    private recordType non_conferenceField;
    
    private recordType in_divisionField;
    
    private recordType homeField;
    
    private recordType awayField;
    
    private recordType overtimeField;
    
    private recordType grassField;
    
    private recordType turfField;
    
    private recordType scored_firstField;
    
    private recordType decided_by_7_pointsField;
    
    private recordType leading_at_halfField;
    
    private recordType last_5Field;
    
    private scoringType pointsField;
    
    private scoringType touchdownsField;
    
    private standingsTypeStreak streakField;
    
    private string idField;
    
    private string marketField;
    
    private string nameField;
    
    /// <remarks/>
    public recordType overall {
        get {
            return this.overallField;
        }
        set {
            this.overallField = value;
        }
    }
    
    /// <remarks/>
    public recordType in_conference {
        get {
            return this.in_conferenceField;
        }
        set {
            this.in_conferenceField = value;
        }
    }
    
    /// <remarks/>
    public recordType non_conference {
        get {
            return this.non_conferenceField;
        }
        set {
            this.non_conferenceField = value;
        }
    }
    
    /// <remarks/>
    public recordType in_division {
        get {
            return this.in_divisionField;
        }
        set {
            this.in_divisionField = value;
        }
    }
    
    /// <remarks/>
    public recordType home {
        get {
            return this.homeField;
        }
        set {
            this.homeField = value;
        }
    }
    
    /// <remarks/>
    public recordType away {
        get {
            return this.awayField;
        }
        set {
            this.awayField = value;
        }
    }
    
    /// <remarks/>
    public recordType overtime {
        get {
            return this.overtimeField;
        }
        set {
            this.overtimeField = value;
        }
    }
    
    /// <remarks/>
    public recordType grass {
        get {
            return this.grassField;
        }
        set {
            this.grassField = value;
        }
    }
    
    /// <remarks/>
    public recordType turf {
        get {
            return this.turfField;
        }
        set {
            this.turfField = value;
        }
    }
    
    /// <remarks/>
    public recordType scored_first {
        get {
            return this.scored_firstField;
        }
        set {
            this.scored_firstField = value;
        }
    }
    
    /// <remarks/>
    public recordType decided_by_7_points {
        get {
            return this.decided_by_7_pointsField;
        }
        set {
            this.decided_by_7_pointsField = value;
        }
    }
    
    /// <remarks/>
    public recordType leading_at_half {
        get {
            return this.leading_at_halfField;
        }
        set {
            this.leading_at_halfField = value;
        }
    }
    
    /// <remarks/>
    public recordType last_5 {
        get {
            return this.last_5Field;
        }
        set {
            this.last_5Field = value;
        }
    }
    
    /// <remarks/>
    public scoringType points {
        get {
            return this.pointsField;
        }
        set {
            this.pointsField = value;
        }
    }
    
    /// <remarks/>
    public scoringType touchdowns {
        get {
            return this.touchdownsField;
        }
        set {
            this.touchdownsField = value;
        }
    }
    
    /// <remarks/>
    public standingsTypeStreak streak {
        get {
            return this.streakField;
        }
        set {
            this.streakField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string market {
        get {
            return this.marketField;
        }
        set {
            this.marketField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/standings-v1.0.xsd")]
public partial class recordType {
    
    private string winsField;
    
    private string lossesField;
    
    private string tiesField;
    
    private decimal wpctField;
    
    private bool wpctFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string wins {
        get {
            return this.winsField;
        }
        set {
            this.winsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string losses {
        get {
            return this.lossesField;
        }
        set {
            this.lossesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string ties {
        get {
            return this.tiesField;
        }
        set {
            this.tiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal wpct {
        get {
            return this.wpctField;
        }
        set {
            this.wpctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool wpctSpecified {
        get {
            return this.wpctFieldSpecified;
        }
        set {
            this.wpctFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://feed.elasticstats.com/schema/nfl/standings-v1.0.xsd")]
public partial class scoringType {
    
    private string forField;
    
    private string againstField;
    
    private string netField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string @for {
        get {
            return this.forField;
        }
        set {
            this.forField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string against {
        get {
            return this.againstField;
        }
        set {
            this.againstField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string net {
        get {
            return this.netField;
        }
        set {
            this.netField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://feed.elasticstats.com/schema/nfl/standings-v1.0.xsd")]
public partial class standingsTypeStreak {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
